name: gym
description: "Gym App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  page_transition: ^2.1.0
  provider: ^6.1.1
  connectivity_plus: ^3.0.6
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  dropdown_button2: ^2.3.9
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  flutter_svg: ^2.0.9
  animated_custom_dropdown: ^2.0.0
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/


  fonts:
    - family: Saira
      fonts:
        - asset: assets/fonts/Saira-Regular.ttf
          weight: 400
        - asset: assets/fonts/Saira-Medium.ttf
          weight: 500
        - asset: assets/fonts/Saira-SemiBold.ttf
          weight: 600
